### ISSUE TITLE
Fix margin in Create topic icons

### ISSUE THREAD

**Issue by HemilTheRebel** [Nalanda-Labs/arth#9]

**Comment by shivshankardayal** [comment]
Fixed

**Comment by HemilTheRebel** [comment]
Where are you? Why have you blocked me?

**Comment by shivshankardayal** [comment]
I do not like people who do not keep their words. If you cannot do something be clear about it.

**Comment by HemilTheRebel** [comment]
I have posted initial preface and introduction. Will continue work during weekend. Check - https://gitlab.com/rahem027/flutter-book

**Comment by shivshankardayal** [comment]
I do not care anymore about it, will do what I can; alone.

**Comment by HemilTheRebel** [comment]
I am sorry

**Comment by shivshankardayal** [comment]
You do not have to be sorry to me. You did what you thought best. Just do not do it to another person. Do not promise what you cannot fulfill.
